---

platform_type: aws
os_type: rhel7

http_proxy: ''
https_proxy: ''

timezone:
  region: Australia
  locality: Melbourne

aws:
  user: ec2-user
  region: overwrite-me
  vpc_id: overwrite-me
  subnet_id: overwrite-me
  source_ami: overwrite-me
  ami_users: ''
  instance_profile: overwrite-me
  install_ssm_agent: true
  install_cloudwatchlogs: true
  root_volume_size: 20
  data_volume_size: 75
  tags:
    - Key: overwrite-me
      Value: overwrite-me

aem:
  profile: aem62_sp1_cfp9
  keystore_password: changeit
  author:
    jvm_mem_opts: "-Xss4m -Xms4096m -Xmx8192m"
  publish:
    jvm_mem_opts: "-Xss4m -Xms4096m -Xmx8192m"
  dispatcher:
    version: 4.2.3
  artifacts_base: overwrite-me
  certs_base: overwrite-me

ci:
  aws:
    platform_types:
      - aws
    aem_versions:
      - aem62
      - aem63
      - aem64
    os_types:
      - rhel7
    components:
      - java
      - author
      - publish
      - dispatcher
      - author-publish-dispatcher
    s3:
      bucket_name: overwrite-me
    iam:
      role_arn: overwrite-me
