---

- name: Create Packer AEM AWS resources stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: "Create AWS SSM Secure String Parameters"
      aws_ssm_parameter_store:
        name: "/aem-opencloud/{{ stack_prefix }}/aem-license"
        description: "License for {{ stack_prefix }} Stack. Delete using the delete job in AEM Opencloud Manager."
        string_type: "SecureString"
        value: "changeme"

    - name: Create AWS resources stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ aws.resources.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../templates/cloudformation/aws-resources.yaml"
        template_parameters:
          StackPrefix: "{{ stack_prefix }}"
          PackerAemS3Bucket: "{{ aws.resources.s3_bucket }}"
          EnableSecretsManager: "{{ aws.resources.enable_secrets_manager | bool }}"
          CreatePackerIAMRole: "{{ aws.resources.create_iam_packer_role | bool }}"
          CreatePackerBucket: "{{ aws.resources.create_s3_bucket | bool }}"
