---
- name: Set configuration tasks
  hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - role: '../../../../ansible-vars-schema-validator/roles/validator'
      vars:
        schema: '../../../validation/stack.yaml'

  tasks:

    - name: Generate Hieradata configuration
      template:
        src: ../../../templates/ansible/hieradata.j2
        dest: ../../../conf/puppet/hieradata/local.yaml
        mode: 0644

    - name: Generate component-specific Hieradata configuration
      template:
        src: ../../../templates/ansible/hieradata-{{ item }}.j2
        dest: ../../../conf/puppet/hieradata/local-{{ item }}.yaml
        mode: 0644
      loop:
        - author-publish-dispatcher

    - name: Generate Packer Variables configuration
      template:
        src: ../../../templates/ansible/packer-vars.j2
        dest: ../../../conf/packer/vars/99_local.json
        mode: 0644

    - name: Add custom AWS tags to Packer template files
      packer_tags:
        template_dir: "../../../templates/packer/{{ platform_type }}/"
        tags: "{{ aws['tags'] }}"
      when:
        platform_type == "aws"

    - name: Add KMS Key ID to launch_block_device_mappings in Packer template files
      packer_kms_key_id:
        template_dir: "../../../templates/packer/{{ platform_type }}/"
        kms_key_id: "{{ aws.encryption.ebs_volume.kms_key_id }}"
      when: aws.encryption.ebs_volume.enable and aws.encryption.ebs_volume.kms_key_id is defined and aws.encryption.ebs_volume.kms_key_id != 'overwrite-me'
